### ISSUE TITLE
[type] loc not working

### ISSUE THREAD

**Issue by crazypool2019** [cynixx3/third-party-miner-installer-for-ethos#25]
Hi @cynixx3 when i install bminer the loc option not work

source <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) bminer install

# [type] [worker] [value]
# ------------------------------------------------------
# loc c94e13 MyMinerName

on pool site show c94e13 , is possible fix this issue ?

when i delete bminer 

source <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) bminer revert

loc option work again....

Great Job !!!!
Really very thanks for "third-party-miner"

**Comment by crazypool2019** [comment]
hi, 
1. gethelp pre-install bminer
http://paste.ethosdistro.com/lavidakuno

check line 79 and 661

79 rack_loc: MrCrazy1
661 su - ethos -c "/opt/miners/ethminer/ethminer-single -U  -P stratum1+tcp://0x2363d956b5a48fb1e8229561cea631cf259bef77.**MrCrazy1**@chl-etc.crazypool.org:7550 -P stratum1+tcp://0x2363d956b5a48fb1e8229561cea631cf259bef77.**MrCrazy1**@usa-etc.crazypool.org:7550 --farm-recheck 200 --dag-load-mode 1  --api-port -3333  --display-interval 1  --cuda-parallel-hash 4     >> /var/run/miner.output 2>&1 &"

2. gethelp with bminer installed
http://paste.ethosdistro.com/vefisaracu
line 79
rack_loc:                                 MrCrazy1
line 661
su - ethos -c "/opt/miners/ethminer/ethminer-single -U  -P stratum1+tcp://0x2363d956b5a48fb1e8229561cea631cf259bef77.MrCrazy1@chl-etc.crazypool.org:7550 -P stratum1+tcp://0x2363d956b5a48fb1e8229561cea631cf259bef77.MrCrazy1@usa-etc.crazypool.org:7550 --farm-recheck 200 --dag-load-mode 1  --api-port -3333  --display-interval 1  --cuda-parallel-hash 4     >> /var/run/miner.output 2>&1 &"

on pool

![image](https://user-images.githubusercontent.com/45013538/51795786-01453780-21c8-11e9-8b0d-075c3a6b3c30.png)

maybe is a problem between bminer and ethminer ?

**Comment by cynixx3** [comment]
The miner start commands are identical. There should be no difference. 

However this is not a use case that was intended for when this was written. Some miner dependencies will break the stock miners from working. This is why a revert action was given, to uninstall each miner when not using it. 

Why install bminer to mine with ethminer?
