### ISSUE TITLE
lolminer hash-monitor

### ISSUE THREAD

**Issue by mzanoli** [cynixx3/third-party-miner-installer-for-ethos#37]
there is a bug in the hash-monitor for lolminer. It connects to api on port 42000, but the correct port is 42043

**Comment by unsivilaudio** [comment]
No.  Its part of the iptables of ethos, all 42xxx ports => 42000.  If you aren't getting hashrate, reboot.

**Comment by unsivilaudio** [comment]
I added another call to clear out the iptables when restarting the miner.  Should help if you are losing hashrate reporting.  Re-run the installer.
