### ISSUE TITLE
XPM Miner

### ISSUE THREAD

**Issue by EvgenRad81** [cynixx3/third-party-miner-installer-for-ethos#48]
Please integrate xpmminer.

http://xpmforall.org
http://coinsforall.io/distr/xpmclient-opencl-10.3-linux.tar.gz
http://coinsforall.io/distr/xpmclient-cuda-10.3-linux.tar.gz

**Comment by cynixx3** [comment]
Hello EvgenRad81,

You are welcome to add the miner to this repo, or have the miner developers add it. Here are some instuctions to help streamline the process: https://github.com/cynixx3/third-party-miner-installer-for-ethos/blob/master/DEVELOPERS.md
