### ISSUE TITLE
Phoenix Miner Switching to epools.txt

### ISSUE THREAD

**Issue by nithronium** [cynixx3/third-party-miner-installer-for-ethos#52]
Hello there, after testing the script and the Phoenix Miner for a bit, I realized that the Phoenix miner gets pool and wallet address data from both epools.txt and the local/remote configuration. Which actually causes problems if your main pool is down, and you don't have a secondary pool configured. Or even in some cases, if two pools are configured but they are both down, the miner switches to the default pool / wallet that was specified at the epools.txt located at /opt/miners/phoenixminer

It took me couple hours to realize that the miner was not mining the dev fee, but actually switched to some other pool. After restarting it, I saw the message "4 pools specified (2 from terminal)" I understood this was the problem.

Please either make the script delete the epool.txt after installing the Phoenix Miner, or, by some extra command, make sure that the two lines (which are defining those 2 extra wallet adresses) are dashed out.

**Comment by cynixx3** [comment]
epools.txt will now be removed on install or update. 

Thank you for the input.
