### ISSUE TITLE
Miniz bad hashrate

### ISSUE THREAD

**Issue by eltech35** [cynixx3/third-party-miner-installer-for-ethos#53]
in hash-monitor, it should be:
tail -50 /var/run/miner.output | grep "$i>" | tr '*' ' ' | tail -1 | cut -d ' ' -f10 
instead of
tail -50 /var/run/miner.output | grep "$i>" | tr '*' ' ' | tail -1 | cut -d ' ' -f12

i think

**Comment by unsivilaudio** [comment]
Its working fine here, but I only have a single gpu.  Can you please `cat /var/run/miner.output | pasteit` and leave the link here so I can do testing.

**Comment by unsivilaudio** [comment]
Make sure the miner has been running for a few minutes, thanks

**Comment by eltech35** [comment]
http://paste.ethosdistro.com/aduxoviriz

Regards,
Christophe TOUZET
Elichain Technology
ctouzet@elichain.com

**Comment by unsivilaudio** [comment]
Ok, I've pushed an update that seems to work for both scenarios.  Please test it and let me know.

**Comment by eltech35** [comment]
Working smootly, thank you very much !

**Comment by unsivilaudio** [comment]
Great.  Thanks
