### ISSUE TITLE
Miniz 1.4o

### ISSUE THREAD

**Issue by eltech35** [cynixx3/third-party-miner-installer-for-ethos#55]
When you will update miniZ to 1.4o, in hash-monitor, the correct field to get the individual gpu hash seems to be f8.

tail -50 /var/run/miner.output | grep "0>" | cut -d '\' -f2 | sed 's/[)*(]/ /g' | cut -d' ' -f8 | tail -1

**Comment by unsivilaudio** [comment]
Dang, I'll look into it.

**Comment by unsivilaudio** [comment]
Again, I need a miner output sample.  Please let your miner run for about 5 minutes and then give me `cat /var/run/miner.output | pasteit` and leave the link here.

**Comment by eltech35** [comment]
Also issue with checksum it seems:

Comparing download with checksum
miniz.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Check of miner files failed, please check your access to git then try again or update miner.settings in repo
