### ISSUE TITLE
gminer with cokucoo29 error

### ISSUE THREAD

**Issue by QQ40451** [cynixx3/third-party-miner-installer-for-ethos#61]
when mine grin in sparkpool ,worker and  wallet should link with '/'   but you use '.'   
 for example : 123@sparkpool.com/rig-123 
Not --user 123@qq.com.rig-123

**Comment by cynixx3** [comment]
unfortunate that it doesn't work with sparkpool but that is the proper format for many other pools. If this is a priority for you please request it in the IRC support at http://ethosdistro.com/kb/#support
