### ISSUE TITLE
(Nvidia) xmrig no libxmrig-cuda.so

### ISSUE THREAD

**Issue by h8J0** [cynixx3/third-party-miner-installer-for-ethos#64]
Running bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) xmrig install nvidia
Starting xming.
Error: xmrig failed to load CUDA plugin
File libxmrig-cuda.so not in the system.

p.s. p. s. xmr-stak does not have this problem.

**Comment by cynixx3** [comment]
Indeed, the nvidia version does not work, the opencl version looks to run though. Sorry but I never saw the benefit to getting this working. I think if it becomes profitable someone will find the nvidia fix and maybe even integrate it.
