### ISSUE TITLE
LOLMINER 1.01 Can`t start after update

### ISSUE THREAD

**Issue by EvgenRad81** [cynixx3/third-party-miner-installer-for-ethos#67]
unrecognised option '--usercfg'
+---------------------------------------------------------+
|     _       _ __  __ _                   _   ___  _     |
|    | | ___ | |  \/  (_)_ __   ___ _ __  / | / _ \/ |    |
|    | |/ _ \| | |\/| | | '_ \ / _ \ '__| | || | | | |    |
|    | | (_) | | |  | | | | | |  __/ |    | || |_| | |    |
|    |_|\___/|_|_|  |_|_|_| |_|\___|_|    |_(_)___/|_|    |
|                                                         |
|              This software is for mining                |
|              Equihash 144/5, 192/7, 210/9               |
|              BeamHash I  (EquihashR 150/5/0)            |
|              BeamHash II (EquihashR 150/5/3)            |
|              BeamHash III                               |
|              ZelHash     (EquihashR 125/4/0)            |
|              CuckarooD 29                               |
|              CuckarooM 29                               |
|              Cuckaroo  30 CTX                           |
|              Cuckatoo  31/32                            |
|                                                         |
|                                                         |
|             Made by Lolliedieb, June 2020               |
+---------------------------------------------------------+
Error: Neither --coin nor --algo nor --benchmark specified.
       lolMiner does not know what to do ;)
       Use -h to get a list of valid parameters. Closing now.

**Comment by cynixx3** [comment]
lolminer changed their start options. It works again.
