### ISSUE TITLE
bminer

### ISSUE THREAD

**Issue by H4xl0r** [cynixx3/third-party-miner-installer-for-ethos#68]
How to Integrate Bminer ? 
I am able to install it via the miner-manager but need to run in manually , not having stats seen by ethos.
Would need some help here if possbile 

running bminer -uri .... 2>&1 /var/run/miner.output to have at least the show miner running.
so not fully integrated ! 

If setting local.conf (yes using local)
to:
globalminer gminer & Settings its falling back to ethminer

**Comment by cynixx3** [comment]
As stated by the readme in this repo only one additional miner can be installed at a time. Make sure bminer is the last miner you installed and it will work fine. 

If this doesn't solve your issue go to ethOS IRC support to further describe your issue, http://ethosdistro.com/kb/#support
