### ISSUE TITLE
I am getting an error "Permission denied"

### ISSUE THREAD

**Issue by SalihACan** [cynixx3/third-party-miner-installer-for-ethos#70]
Hi, I have 3 rx470 4gb in my rig, I have been using your miner on ethos for 1 month, there was no error on usb installation, but today I changed my installation to ssd and repeated all steps in same way, but now I am getting an error.
Cannot exec '/opt/miners/phoenixminer/PhoenixMiner': Permisiion denied
I tried to chmod things.. but it doesn't work. What should I do.?

Also I want to add something that the folder name was different than PhoenixMiner at the first place,(something like PhoenixMiner_5 tar gz...) at that time I got another error that "No such file" then I changed name to PhoenixMiner.

**Comment by cynixx3** [comment]
Please join the ethOS IRC support channel http://ethosdistro.com/kb/#support
