### ISSUE TITLE
how to dualminer Ethereum - blake2s on phoenixminer in ethos

### ISSUE THREAD

**Issue by veraphon** [cynixx3/third-party-miner-installer-for-ethos#74]
can you sample config?

**Comment by cynixx3** [comment]
https://github.com/cynixx3/third-party-miner-installer-for-ethos#ethos-config-sample

**Comment by veraphon** [comment]
i try


globalminer phoenixminer
maxgputemp 80
stratumproxy enabled
proxywallet 0xc85a21D50313d1753f75695dDe50BC355aEAD374
proxypool1 ssl://asia1.ethermine.org:5555
#proxypool2 us1.ethermine.org:4444
flags -proto 3
globalfan 85
dualminer enabled
dualminer-coin blake2s
dualminer-pool blake2s.usa.nicehash.com:3361
dualminer-wallet 1CvL6uBnAWLbTsg2PR1kMoNH5JKM1r6Tgz



but not work

Eth speed: 151.404 MH/s, shares: 3/0/0, time: 0:01
GPUs: 1: 24.506 MH/s (0) 2: 27.170 MH/s (0) 3: 22.635 MH/s (0) 4: 24.587 MH/s (0) 5: 24.492 MH/s (0) 6: 28.016 MH/s (3)
B2S speed: 0.000 MH/s, shares: 0/0/0
GPUs: 1: 0.000 MH/s (0) 2: 0.000 MH/s (0) 3: 0.000 MH/s (0) 4: 0.000 MH/s (0) 5: 0.000 MH/s (0) 6: 0.000 MH/s (0)



can you suggest?

**Comment by cynixx3** [comment]
You are not having a problem with this script or with the miner, for generic ethOS support please follow the instructions in this link. http://ethosdistro.com/kb/#support
