### ISSUE TITLE
can't install ethminer

### ISSUE THREAD

**Issue by danizaharie** [cynixx3/third-party-miner-installer-for-ethos#76]
I am trying to install ethminer but get the next error:

`root@29310b 192.168.88.109 [130.5 hash] /opt/miners/ethminer bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) ethminer install
Fri Feb  5 09:13:32 CST 2021
/dev/fd/63: line 42: [: : integer expression expected
Move to a temporary work space
Getting latest release of miner
Download failed. Please check your firewall or git access and try again.
`

**Comment by cynixx3** [comment]
Please use these instructions for official support: http://ethosdistro.com/kb/#support
