### ISSUE TITLE
I can't update ethminer, get download failed

### ISSUE THREAD

**Issue by danizaharie** [cynixx3/third-party-miner-installer-for-ethos#77]
I can't update ethminer, get download failed, any idea?

`10:09 AM root@aabcds 192.168.1.101 [322.4 hash] /opt/ethos/bin # bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) ethminer update
Tue Feb  9 10:09:21 CST 2021
/dev/fd/63: line 42: [: : integer expression expected
Move to a temporary work space
Getting latest release of miner
Download failed. Please check your firewall or git access and try again.
`

**Comment by cynixx3** [comment]
Same as last time, Please use these instructions for official support: http://ethosdistro.com/kb/#support
