### ISSUE TITLE
miner-installer is failing to download release for ethminer

### ISSUE THREAD

**Issue by dsolovyov** [cynixx3/third-party-miner-installer-for-ethos#81]
Hello,

There is no valid instance for 'ethminer' release in 

https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/releases

As a result, miner-installer failing to find, download and install/update ethminer.

D.

**Comment by cynixx3** [comment]
Fixed.

FYI: You are likely going to want to use a more modern miner,  Ethminer is over 2 years old at this point and unlikely to work for many GPU's.
