### ISSUE TITLE
Linux TeamRedMiner update installs armhf version

### ISSUE THREAD

**Issue by DynamicBits** [cynixx3/third-party-miner-installer-for-ethos#88]
When attempting to update TeamRedMiner on Linux, the linux-armhf version is installed instead of the regular linux version.

When I passed the download URL via DOWNLOAD_URL, the correct version was installed:

`DOWNLOAD_URL=https://github.com/todxx/teamredminer/releases/download/v0.10.7/teamredminer-v0.10.7-linux.tgz ./miner-manager teamredminer update`

It looks like armhf was added as of [v0.10.1](https://github.com/todxx/teamredminer/releases/tag/v0.10.1) and it appears before the regular linux release, so it gets parsed first.

**Comment by cynixx3** [comment]
Thanks for the research! Script should skip the armhf downloads now.
